### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by vimcwal** [GuanYixuan/pyJianYingDraft#1]
大佬你好，快速上手中的例子，生成一个draft_content.json文件是替换进原来的草稿文件中吗？还是直接生成draft_content.json在草稿目录下，打开剪映就能自动识别出来？

**Comment by GuanYixuan** [comment]
是替换掉原来的草稿文件。因为目前本工具还不会自动生成剪映草稿（剪映工程）的整个结构，所以推荐的使用方式是：

- 在剪映里创建一个空草稿
- 关闭剪映
- 直接用生成的draft_content.json覆盖掉原来的draft_content.json
- 重新用剪映打开那个草稿，剪映会自动识别更改

在代码里面就类似于
```
# 保存草稿
script.dump("<某些路径>/JianyingPro Drafts/9月4日/draft_content.json")
```
其中那个`9月4日`是你新创建的剪映草稿

**Comment by vimcwal** [comment]
我试试，感谢哈
