### ISSUE TITLE
模板草稿中含有调节轨道时加载失败

### ISSUE THREAD

**Issue by linZlee** [GuanYixuan/pyJianYingDraft#14]
![M`1LRQ72WX{F013V0%F6OFR](https://github.com/user-attachments/assets/712d66fe-ac80-420c-9001-83ae0860e5b1)
你好，请问下在运行复制草稿报这个错是为什么呢，但草稿仍然被复制了

**Comment by GuanYixuan** [comment]
这个是复制结束后尝试打开新草稿进行编辑时报的错，看起来是你的模板草稿里面有一种`adjust`（调节/调整？）轨道目前还未被收录到`Track_type`中导致的。这个问题应该是容易修复的，我下午更新时将其加进去即可。

顺便问一句，这个`adjust`轨道对应的是剪映中的什么功能，因为此前还没有预料到此类轨道的存在

**Comment by linZlee** [comment]
![6_N` CV1T_5CCP3`93}UPI6](https://github.com/user-attachments/assets/6de54acb-eab5-475b-ae59-be34d675b56a)
![OXI9$N)2PESZNUW$Z0{89GI](https://github.com/user-attachments/assets/a9d69398-40b1-4e10-9649-ae4b35d8e28b)
应该是我单独添加了一个调节的选项

**Comment by GuanYixuan** [comment]
了解。现在下午更新的代码应该能够兼容调节轨道了，可以测试一下

**Comment by linZlee** [comment]
感谢博主

**Comment by linZlee** [comment]
博主，另外我在采用根据片段替换后，新的视频素材的尺寸大小与原素材不一致（新的视频素材没有进行裁剪），这种目前可以实现吗

**Comment by GuanYixuan** [comment]
大小不一致也可以替换，当然替换出来的片段大小也不一样。如果希望裁剪的话可以对新素材设置`Crop_settings`属性，然后再进行替换。目前还不支持在替换时重新调节缩放比例，因为这是个片段属性而不是素材属性
