### ISSUE TITLE
是否可以支持贴纸功能

### ISSUE THREAD

**Issue by tyshaokr** [GuanYixuan/pyJianYingDraft#18]
看了下基于目前框架设计，贴纸功能的实现需要涉及的配置参数有点多，实现起来难度比较大，但是是一种很好的挑战。可以实现一下吗？

**Comment by GuanYixuan** [comment]
由于贴纸的种类太多，不像特效那样能够枚举，可能会先考虑实现一个“提取素材”功能来从已有的（模板）json文件中提取贴纸元数据（`resource_id`等）。此后用户就可以比较方便地根据这个元数据添加对应贴纸了

**Comment by tyshaokr** [comment]
> 由于贴纸的种类太多，不像特效那样能够枚举，可能会先考虑实现一个“提取素材”功能来从已有的（模板）json文件中提取贴纸元数据（`resource_id`等）。此后用户就可以比较方便地根据这个元数据添加对应贴纸了

是的，提供一个配置文件专门用来配置可选的贴纸👍

**Comment by tyshaokr** [comment]
另外，是否考虑建一个交流群，不断迭代这个框架，现在很多人有实现剪映自动化的需求。

**Comment by GuanYixuan** [comment]
> 另外，是否考虑建一个交流群，不断迭代这个框架，现在很多人有实现剪映自动化的需求。

由于个人时间有限，可能短时间内不会建立一个“群”，不过可以考虑将此repo的讨论区打开，这样讨论相对也能更丰富一些

**Comment by GuanYixuan** [comment]
现在本项目已初步支持贴纸片段`Sticker_segment`，其中需要的`resource_id`参数可以参考[此方法](https://github.com/GuanYixuan/pyJianYingDraft?tab=readme-ov-file#%E6%8F%90%E5%8F%96%E7%B4%A0%E6%9D%90%E5%85%83%E6%95%B0%E6%8D%AE)获取
