### ISSUE TITLE
有打算支持字幕吗

### ISSUE THREAD

**Issue by wxbool** [GuanYixuan/pyJianYingDraft#2]
有打算支持字幕吗，感谢

**Comment by GuanYixuan** [comment]
目前来看，从`.srt`等文件中导入字幕的功能可以随着对文本功能的完善一并加入，但估计短时间内不会支持诸如“识别字幕”这类需要调用剪映本身函数的功能

**Comment by wxbool** [comment]
好的，只要能正常创建字幕块就行，期待更新

**Comment by GuanYixuan** [comment]
此功能目前已实现，可调用`Script_file.import_srt`方法来导入`srt`字幕并支持设置整体偏移，字幕默认模仿剪映自身的样式

**Comment by wxbool** [comment]
目前字幕导入可以使用，感谢感谢！希望有空可以支持更完善的字幕样式设置，比如字幕对齐（现在有文本对齐，但对字幕无效），字幕背景，字幕阴影等等

**Comment by GuanYixuan** [comment]
嗯，我也是经你提醒后才发现各片段有自己的“空间摆放”对齐方式，目前的文本对齐是在“文本框”内的对齐，二者不是同一个功能。实现“空间对齐”的难点是需要事先计算字幕块的大小，这个还得再思考一下

字幕的背景、阴影等特性就和文本的完全相通了，一旦文本侧实现了（如，描边）就能很快移植过来
