### ISSUE TITLE
可以复制模板，但是复制后无法自动打开模板进行编辑

### ISSUE THREAD

**Issue by LittleTerry** [GuanYixuan/pyJianYingDraft#20]
按照示例代码，程序不报错。可以复制模板，但是无法自动打开复制后的模板。剪映用的是5.9，系统win11，python版本3.10.11
![image](https://github.com/user-attachments/assets/fdea3d7c-917e-46b2-927b-2685eb981eec)

**Comment by LittleTerry** [comment]
测试了python 3.11.9，依旧不行

**Comment by GuanYixuan** [comment]
这里是指剪映不会自动加载那个`test_template`吗？`duplicate_as_template`会读取复制后的草稿并作为一个可编辑的`Script_file`对象返回，而不会在剪映里将它打开，可能readme里写的有一些歧义

**Comment by LittleTerry** [comment]
哦哦，readme里说“同时打开新草稿供编辑”，我以为指的是在剪映里打开它。
那有什么方法可以在剪映里打开指定的模板吗？比如让剪映自动加载那个test_template。
谢谢！

**Comment by GuanYixuan** [comment]
其实`Jianying_controller.export_draft`里面有一段代码（41~50行）会打开指定的草稿，不过目前没有独立封装成函数

需要注意的是，这段代码需要在剪映主菜单已经刷新出了你刚复制的草稿后才能正常运行

**Comment by LittleTerry** [comment]
好的谢谢，我去试试
