### ISSUE TITLE
替换音频时，报错“KeyError: 'material_name'”

### ISSUE THREAD

**Issue by LittleTerry** [GuanYixuan/pyJianYingDraft#21]
我的草稿中只有一个音频，想要替换音频时，报错如下
![image](https://github.com/user-attachments/assets/8f1dfc77-e55c-4241-b40b-ce801b8d2387)

![image](https://github.com/user-attachments/assets/f1e041d4-7231-4dbe-b1ad-cb8c7ae550f5)

**Comment by GuanYixuan** [comment]
这确实是个bug，原因是音频和视频素材的“名称”属性不一样，一个叫`name`，一个叫`material_name`。最新版本的代码应该已经修复了

**Comment by LittleTerry** [comment]
感谢您的修复！经测试，该替换方法已经正常。谢谢！
