### ISSUE TITLE
程序新建的草稿，剪映无法实时显示

### ISSUE THREAD

**Issue by 1u3ec** [GuanYixuan/pyJianYingDraft#27]
使用模板模式复制了一个新草稿，但是剪映首页无法实时显示该草稿，导致导出的时候无法找到新草稿。

**Comment by GuanYixuan** [comment]
这个应该主要是剪映自身不会实时刷新导致的，其实没有太好的方法。不过可以考虑将草稿都生成完之后再打开剪映，或生成草稿之后让剪映先点进去某个已有的草稿再退出来以起到刷新的目的

**Comment by 1u3ec** [comment]
> 这个应该主要是剪映自身不会实时刷新导致的，其实没有太好的方法。不过可以考虑将草稿都生成完之后再打开剪映，或生成草稿之后让剪映先点进去某个已有的草稿再退出来以起到刷新的目的

感谢解答。还有一个问题，在使用模板模式替换图片素材时，图片不加转场是可以正常替换的，但是如果添加有转场，程序执行替换的时候无法找到素材中的图片，请问这个怎么解决呢？
![20241212154902](https://github.com/user-attachments/assets/93f9ab1f-b976-46d8-a149-f0446a30a36a)
![20241212161106](https://github.com/user-attachments/assets/71315f29-7789-42f1-9585-1fa9003de310)
