### ISSUE TITLE
想问一下你是使用什么工具对剪映页面元素控件进行可视化分析的

### ISSUE THREAD

**Issue by jiangzituozou** [GuanYixuan/pyJianYingDraft#29]

**Comment by GuanYixuan** [comment]
用的其实就是微软官方发布的`inspect`

**Comment by jiangzituozou** [comment]
> 使用的其实就是微软官方发布的`inspect`

我使用inspect能看到剪映专业版窗口，但是展开后里面再也没有任何元素，分析别的应用可以看见里面的元素，使用的最新版剪映，这个与剪映版本或inspect版本有关系吗

**Comment by GuanYixuan** [comment]
因为我只inspect过剪映5.9并且能看到它的控件结构，所以也许真的跟剪映有关？

使用的inspect来自Windows SDK 10.0.19041.0（64位）
