### ISSUE TITLE
希望增加文字位置的设置

### ISSUE THREAD

**Issue by wxbool** [GuanYixuan/pyJianYingDraft#3]
希望增加文字位置的设置，感谢感谢

**Comment by GuanYixuan** [comment]
这个功能作为导入字幕的前序功能刚刚实现，目前可以利用`Text_segment`的`clip_settings`参数指定
粗略观察了一下，剪映自身导入的字幕类似于取`style = Text_style(size=5.0, align=1)`及`clip_settings = Clip_settings(transform_y=-0.8)`的样式

**Comment by wxbool** [comment]
好的，我试试，期待更新！
