### ISSUE TITLE
请问替换草稿素材的功能可以优先开发吗

### ISSUE THREAD

**Issue by quain4code** [GuanYixuan/pyJianYingDraft#5]
您好，非常感谢分享这个项目出来。请问，计划里列的模板方式加载进行替换资源的功能准备什么时候开始哈，最近有用到，或者提供下思路一起来搞。

**Comment by GuanYixuan** [comment]
这两天可能会看一下具体实现的方法

目前计划实现的功能是：
-  导入模板，保留其中所有内容
- 允许对模板内的音视频片段进行素材替换
- 暂不支持对模板内的片段进行其它修改（如修改特效、修改转场、修改淡入淡出时长等）
- 支持在模板的基础上增加新的轨道，并在新的轨道上自由添加片段（就像非模板模式一样）

大体思路是将模板json中需要修改的部分读入为`pyJianYingDraft`中的对象（`Audio_segment`、`Video_segment`之类的），这样就能够应用现成的方法对其进行修改（然后重新导出），不修改的部分则与导出内容直接合并。

读入为`pyJianYingDraft`对象的部分越多，能够对模板内容进行的修改就越自由，但是实现起来会更复杂

**Comment by quain4code** [comment]
感谢您的回复，替换素材大部分需求都是复用原有效果，只是替换视频、音频素材内容，和在剪映里拖拽替换保留原有效果。

目前是有对这个模板json对象的读、写模块吗？

**Comment by GuanYixuan** [comment]
目前"读"的部分已经基本实现（`Imported_track`和`Imported_segment`类），但替换的部分还有一些尚未明确的点。若有兴趣可以讨论一下：

- 如何指定轨道？（使用轨道名称是最好的，但导入的轨道不一定有名称）
- 如何指定要替换的片段？（同样，导入的片段不一定有名称）
- 原始片段与替换后素材不等长时，提供哪些处理方式？

**Comment by quain4code** [comment]
https://www.bilibili.com/video/BV1p14y1f7UK/?spm_id_from=333.999.0.0&vd_source=de250436065e4075cb91b6362e6389ed
多轨道问题这个up主他实现了，应该是json上有标记或者按数组位置区分，我还没仔细看那个json

**Comment by GuanYixuan** [comment]
行，那初步先根据轨道和片段的index来区分吧

**Comment by quain4code** [comment]
感谢大佬哈

**Comment by GuanYixuan** [comment]
这个功能目前已经发布了（参见readme相关部分）。由于仍处在实验阶段，若遇到问题欢迎反馈！

**Comment by quain4code** [comment]
好的 一大早看到 感谢哈 我来测试

**Comment by quain4code** [comment]
测试过了，可以跑通。

不过有个使用上的问题，给大佬提供一下反馈。

就是一般使用这种模板替换素材的，一般是以原来模板的素材时长为准，新加入的素材要去匹配原有模板的时长，所以下面这两种方式可能不太适合用。我自己在handle_extend上加了cut_tail的模式。

另外，本项目还缺少了保存时，新增一个项目草稿的功能，这块我在补充。

**Comment by quain4code** [comment]
好的 我整完提上来
