### ISSUE TITLE
可否提供独立轨道的特效添加方法

### ISSUE THREAD

**Issue by pretty2015** [GuanYixuan/pyJianYingDraft#6]
看说明文档中的使用方法是添加到片段上的特效。 有些特效是应用于特效轨道的特效，不知道如何添加。偿试读了下源码，也没找到方法。 但看说明文档中已经勾选了此功能。 再次感谢！

**Comment by GuanYixuan** [comment]
添加特效片段和滤镜片段的方法分别是`Script_file.add_effect`和`Script_file.add_filter`，具体用法可以查看它们的注释。
时间有限还没来得及写相应的教程

**Comment by pretty2015** [comment]
感谢提醒，已成功添加。
