### ISSUE TITLE
关于替换素材模式以及复制已有草稿

### ISSUE THREAD

**Issue by GuanYixuan** [GuanYixuan/pyJianYingDraft#8]
来自issue #5，@quain4code指出：
“一般使用这种模板替换素材的，一般是以原来模板的素材时长为准，新加入的素材要去匹配原有模板的时长，所以下面这两种方式可能不太适合用。我自己在handle_extend上加了cut_tail的模式。

另外，本项目还缺少了保存时，新增一个项目草稿的功能，这块我在补充。”

**Comment by quain4code** [comment]
大佬，对文本轨道的文字内容进行替换，现有代码有做预留空间吗？
我在看您的代码，想看看能不能加入这块

**Comment by quain4code** [comment]
大佬，复制已有草稿的代码我加上去了，逻辑就是先复制一份重命名后进行修改。下面是代码，比较简单


# 复制一份原有的模板项目，然后重命名
def copy_files_and_rename_folder(src_folder, dst_folder_new_name):
    # 确保目标文件夹不存在，如果不存在则创建
    dst_folder = os.path.join(os.path.dirname(src_folder), dst_folder_new_name)
    if not os.path.exists(dst_folder):
        os.makedirs(dst_folder)
    else:
        print(f"{dst_folder_new_name} 该文件夹已存在！")
        return

    # 遍历源文件夹
    for item in os.listdir(src_folder):
        # 拼接完整的文件或文件夹路径
        src_item_path = os.path.join(src_folder, item)
        dst_item_path = os.path.join(dst_folder, item)

        # 如果是文件，则复制
        if os.path.isfile(src_item_path):
            shutil.copy2(src_item_path, dst_item_path)
        # 如果是文件夹，则递归复制（如果需要）
        elif os.path.isdir(src_item_path):
            shutil.copytree(src_item_path, dst_item_path)

===========
# demo代码

# 剪映草稿的地址
jianying_draft_folder_path = "D:/剪印/JianyingPro Drafts/"
# 模板项目文件名
reference_project_folder_name = "20240923-8"
# 模板项目路径
reference_project_path = f"{jianying_draft_folder_path}{reference_project_folder_name}"

# 复制一份模板项目，并且重命名
new_project_folder_name = "20240924-11"

copy_files_and_rename_folder(reference_project_path, new_project_folder_name)

# 对应项目草稿draft_content.json的路径
draft_loc_str = f"{jianying_draft_folder_path}{new_project_folder_name}/draft_content.json"

# 业务代码

# 最后保存
script.dump(draft_loc_str)

**Comment by GuanYixuan** [comment]
好的，我这边整理一下

关于文本片段内容的替换，现有代码其实是留有空间的，但可能需要的修改幅度有点大。目前导入的文本轨道还是以原始json的格式存储在`Static_track`的`raw_data`里。如果替换文字这个功能用得很广泛的话我也可以这周加进列表里实现一下。

**Comment by quain4code** [comment]
感谢大佬，还是挺有用的，市面上这些基于剪映模板进行替换素材混剪的，基本也是换视频、音频素材，以及文本标题。

**Comment by GuanYixuan** [comment]
说的很在理，那就把替换文本片段内容的功能加入列表中吧。另外按照这个逻辑的话，假如能够控制剪映自动导出指定的一系列草稿，是不是也会比较有用？

**Comment by quain4code** [comment]
哈哈 所见略同 我用RPA做了一个自动导出的。用python的auto库也可以，就是用图像识别做定位。这两个方案我之前都做过，用RPA就简单一点。

**Comment by GuanYixuan** [comment]
嗯，RPA确实挺不错的，这个项目到时候可能也会“低配”地加一个用uiautomation实现的版本。

现在cut_tail（代码里称`cut_material_tail`）是`handle_extend`的默认值。从已有模板复制一份然后再修改的功能则放在`Draft_folder.duplicate_as_template`方法中了

**Comment by quain4code** [comment]
看到了 感谢大佬

**Comment by quain4code** [comment]
替换了新的代码，测试了一下，目前没发现问题，是简洁了很多。

```
# 剪映草稿的地址
jianying_draft_folder_path = "D:/剪印/JianyingPro Drafts/"

new_draft = draft.Draft_folder(jianying_draft_folder_path)

# 模板项目文件名
reference_project_folder_name = "20240923-8"

# 复制一份模板项目，并且重命名
current_time = datetime.datetime.now()
# 格式化时间字符串，精确到分秒
current_time_str = current_time.strftime("%m%d%H%M%S")
new_project_folder_name = current_time_str  # "0924153619"

script = new_draft.duplicate_as_template(reference_project_folder_name, new_project_folder_name)

# 业务代码

script.save()

```

**Comment by quain4code** [comment]
大佬给力，我看新增了文本的代码，是这个功能做好了吗

**Comment by GuanYixuan** [comment]
是的，但目前这个`Script_file.replace_text`函数测试得还比较少，有兴趣的话可以先行测试反馈一下。如果今天有空我可能会把它对应的教程补上
